services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=avaliacao_hospital
    ports:
      - 8001:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    image: djhony/webserver:1.0
    volumes:
      - ./app:/var/www/html
    ports:
      - 8000:80
    links:
      - db
    depends_on:
      - db
    tty: true